language: node_js
node_js:
  - "0.10"

after_success:
  - chmod +x ./scripts/*.sh
  - chmod +x ./scripts/for-travis/*.sh
  - ./scripts/for-travis/build-and-deploy.sh

env:
 global:
 - GH_REF: github.com/piscis/reactes6.git
 - secure: x6wxlBAmF3ky5LWkiYi9mRGbfkSF5zV3E8MM+KFi7h5KdPAudur7SxfDvUh9/jLKnAQff8RqD0UFnSWJ6pZ1GLFuacHpfajc3ZYET378UMZilkP3LCXc55w6SzAiQYl4RTDLTjR/H+7Tj6fJb6PcC07bzR4ZIRqnB6KGQPEgousoHv6MZ4rkmkJKPuafcC8w6E7CJXakOfEQpRhk6YWxO2Ij2WsKE11nHk0OeLvC+rKLemC7krtpXSppTJq0e/iajccrGUEfQU970Y9rF0oGIzfLcdqcr3vW+cvHC3xNpJ/ti8FR7L6E0TQQmN2L3oaBC0a2KaBakpVtpbHfzP2t6ph43EHCJfLvVunf7CwWKsYrYacOwbCccdupwzJl5wnJOQofpsHeW9snd2OPy2IMfOmoiWydb7wP8Dse3OqMxYpK602rfl20GceXJUnmtASmiw5X6ZpI899tulzZ0iVU8Ia5KR2O/+pf0/1HeDEqK9+gB6lb/0OIcG8Laz1zrYPWUZqqyWGRw/icg4is6x/REDMu74YbUcTXIlNTr6TrjJDX3dKJGyUaSWBEpf0yUGwMMgFOrwxvLxs+tm9OCwmkfAlFSU4Zhh8SkMlaJHeacpDJWgC4O8jD4UlCn8QDDyy/1EhCAoyyc2HnAEUW8s7QLZqRFu448PNk4sYJiXpLKIY=
